stratton:
  name: Stratton Mountain Resort
  data_files:
    boundaries: data/stratton/boundaries.geojson
    osm_features: data/stratton/osm_features.geojson
  tree_config:
    min_area_for_trees: 5000
    small_area_threshold: 25000
    medium_area_threshold: 100000
    trees_per_small_hectare: 2
    trees_per_medium_hectare: 4
    trees_per_large_hectare: 15
    max_trees_per_polygon: 40
    min_trees_per_polygon: 1
    random_seed: 42
