# Resort Configuration for GeoJSON Processing
# Each resort defines data paths and processing parameters

stratton:
  name: "Stratton Mountain Resort"
  center: [-72.907706, 43.101027]
  zoom: 14
  bounds:
    southwest: [-72.925698, 43.088701]
    northeast: [-72.889714, 43.113352]

  data_files:
    boundaries: "data/stratton/boundaries.geojson"
    osm_features: "data/stratton/osm_features.geojson"

  tree_config:
    # Area thresholds for tree generation
    min_area_for_trees: 5000 # sq meters - minimum polygon area to generate trees
    small_area_threshold: 25000 # sq meters (2.5 hectares)
    medium_area_threshold: 100000 # sq meters (10 hectares)

    # Density settings (trees per hectare)
    trees_per_small_hectare: 2 # for small areas
    trees_per_medium_hectare: 4 # for medium areas
    trees_per_large_hectare: 15 # for large areas

    # Limits
    max_trees_per_polygon: 40 # maximum trees per individual polygon
    min_trees_per_polygon: 1 # minimum trees per polygon

    # Random seed for reproducible results
    random_seed: 42

  # Zone styling properties (added to GeoJSON properties)
  zone_styling:
    slow_zone:
      stroke_color: "#FFFF00"
      stroke_opacity: 1.0
      fill_color: "#FFFF00"
      fill_opacity: 0.5
    closed_area:
      stroke_color: "#FF0000"
      stroke_opacity: 1.0
      fill_color: "#FF0000"
      fill_opacity: 0.7
    beginner_area:
      stroke_color: "#FFFF00"
      stroke_opacity: 1.0
      fill_color: "#FFFF00"
      fill_opacity: 0.4
    ski_area_boundary:
      stroke_color: "#000000"
      stroke_opacity: 1.0
      stroke_width: 3

mammoth:
  name: "Mammoth Mountain"
  center: [-119.037848, 37.650954]
  zoom: 13
  bounds:
    southwest: [-119.058, 37.635]
    northeast: [-119.018, 37.666]

  data_files:
    boundaries: "data/mammoth/MAM_boundaries_2025.geojson"
    osm_features: "data/mammoth/osm_features.geojson"

  tree_config:
    min_area_for_trees: 5000
    small_area_threshold: 25000
    medium_area_threshold: 100000
    trees_per_small_hectare: 1 # Sparser for California mountains
    trees_per_medium_hectare: 3
    trees_per_large_hectare: 10
    max_trees_per_polygon: 35
    min_trees_per_polygon: 1
    random_seed: 42

  zone_styling:
    slow_zone:
      stroke_color: "#FFFF00"
      stroke_opacity: 1.0
      fill_color: "#FFFF00"
      fill_opacity: 0.5
    closed_area:
      stroke_color: "#FF0000"
      stroke_opacity: 1.0
      fill_color: "#FF0000"
      fill_opacity: 0.7
    beginner_area:
      stroke_color: "#FFFF00"
      stroke_opacity: 1.0
      fill_color: "#FFFF00"
      fill_opacity: 0.4
    ski_area_boundary:
      stroke_color: "#000000"
      stroke_opacity: 1.0
      stroke_width: 3
